# Generated by Django 3.1.5 on 2021-01-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210128_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
