# Generated by Django 3.1.5 on 2021-01-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_subject_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='comment',
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.subject')),
            ],
        ),
    ]
