# Generated by Django 3.1.5 on 2021-01-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210128_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Subject',
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.subject'),
        ),
    ]
